### ISSUE TITLE
Scope issues

### ISSUE THREAD

**Issue by luobu-code** [LiuGalaxy/CRLC#1]
The longitude and latitude of the lower left corner have been given, but how to calculate the longitude and latitude of other corners？

**Comment by luobu-code** [comment]
I guess I got it that CRLC products are provided in a 1 * 1 degree tile pattern, so the sitting angle plus 1 degree latitude and longitude?

**Comment by LiuGalaxy** [comment]
> I guess I got it that CRLC products are provided in a 1 * 1 degree tile pattern, so the sitting angle plus 1 degree latitude and longitude?

Thanks for your question, the maps are provided in a 1 * 1 degree tile pattern, just plus 1 degree latitude and longitude.
